### ISSUE TITLE
Duda con info.json

### ISSUE THREAD

**Issue by josuearrieta** [luiskarlos/IA-117#3]
Se debe crear un .json por cada ejercicio/tarea/proyecto realizado.

Sin embargo para la tarea1-fsm qué debe contener este json? Ya que no posee atributos de score, url, y el url de hackerrant ? Solo omitimos esos campos? Los dejamos vacíos?

**Comment by ghost** [comment]
Creo que la de FSM era para calentar en el curso, me parece que el Profe dijo que esa no era tarea, que solo era práctica.
